services:
  ufc-analytics:
    build: .
    ports:
      - "8888:8888"   # Jupyter Lab
      - "8501:8501"   # Streamlit (for later)
    volumes:
      - .:/app        # Sync local files with container
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''